FusionIIIT/Fusion-mobile

README.md
ios/Runner.xcodeproj/project.xcworkspace/contents.xcworkspacedata

Flutter 2.0 supports Web in stable. 
Modified files for 2.0.

Bumped Flutter to 2.0

---

lib/main.dart
lib/screens/Complaint/ComplaintHistory/complain_history.dart
lib/screens/Complaint/Constants/constants.dart
lib/screens/Complaint/Feedback/feedback.dart
lib/screens/Complaint/LodgeComplaint/lodge_complaint.dart
lib/screens/Complaint/complaint.dart
lib/screens/Login and Dashboard/Components/side_drawer.dart

Flutter 1.22.5
Tools • Dart 2.12.0 (build 2.12.0-259.8.beta)
Complaint module
There are 5 dart Files inside the new created Complaint Module which is inside the screens folder. Routs are added in main.dart file.

Created Complaint Module

---

lib/screens/Library/Book_Search.dart
lib/screens/Library/dues.dart
lib/screens/Library/home_screen.dart
lib/screens/Library/issued_items.dart
lib/screens/Library/side_drawer.dart

Flutter 1.22.5
Tools • Dart 2.12.0 (build 2.12.0-259.8.beta)
Library module
There are 5 dart Files inside the new created Library Module which is inside the screens folder.

Added Library Module

---

lib/screens/Academic/academic_home_page.dart
lib/screens/Complaint/ComplaintHistory/complain_history.dart
lib/screens/Complaint/complaint.dart
lib/screens/Gymkhana/Homepage.dart
lib/screens/Gymkhana/Polls.dart
lib/screens/Gymkhana/Record.dart
lib/screens/Library/Book_Search.dart
lib/screens/Library/dues.dart
lib/screens/Library/home_screen.dart
lib/screens/LoginandDashboard/login_page.dart
lib/screens/Profile/Menus/achievements_menu.dart
lib/screens/Profile/Menus/educationMenu.dart
lib/screens/Profile/profile.dart
lib/services/login_service.dart

Updated Widgets to the newest guidelines of Flutter 2.0.
Added TODOs for correction.

Refactored and added TODOs

---

android/settings_aar.gradle
lib/screens/LoginandDashboard/login_page.dart

Validators use to check empty fields and password length.
Alert Box use to show Username/Password is incorrect.

Adding Validators and Alert Dialog Box 

---

lib/models/notification.dart
lib/screens/LoginandDashboard/DashboardComponents/cardItems.dart
lib/services/dashboard_service.dart

Added Notification Read Unread.
Setstate and Streambuilder Configurations are left and awaiting Profile integration.

Notification Read Unread API added

---

lib/Components/side_drawer.dart
lib/models/notification.dart
lib/models/profile.dart
lib/screens/LoginandDashboard/DashboardComponents/cardItems.dart
lib/screens/Profile/Menus/profileMenu.dart
lib/screens/Profile/profile.dart
lib/services/profile_service.dart

Files Added-:
- services/profile_service.dart - Service worker to fetch ProfileData
- models/profile.dart -Model of ProfileData
Changes-:
- Components/side_drawer.dart - Added click support on Profile ModulesCard
- models/notification.dart - Fixed minor bug
- DashboardComponents/cardItems.dart - Fixed minor bug
- Profile/menus/profileMenu.dart - Displayed profileData fetched from profile_service
- Profile/profile.dart - Displayed profileData and added support to call Menu Widgets with profileData

Integrated Profile API and fixed minor bugs

---

lib/main.dart
lib/screens/Profile/Menus/achievements_menu.dart
lib/screens/Profile/Menus/educationMenu.dart
lib/screens/Profile/Menus/skillsMenu.dart
lib/screens/Profile/Menus/workExperiencesMenu.dart

Refactored and added views in profile .

Added Static View for viewing profile details

---

lib/screens/Profile/Menus/educationMenu.dart
lib/screens/Profile/Menus/workExperiencesMenu.dart
lib/screens/Profile/profile.dart

Flutter 2.0.1
Tools • Dart 2.12.0
Description- workExperience Menu now shows realtime data of Internships and projects with API.
Screenshots- 
<p float="left">
</p>

Work experience view API integrated in profile

---

lib/screens/Profile/Menus/achievements_menu.dart
lib/screens/Profile/Menus/educationMenu.dart
lib/screens/Profile/Menus/profileMenu.dart
lib/screens/Profile/Menus/skillsMenu.dart
lib/screens/Profile/Menus/workExperiencesMenu.dart

Refactored code for profile Module.

Refactored profile Module

---

lib/Components/side_drawer.dart
lib/main.dart
lib/models/profile.dart
lib/screens/LoginandDashboard/dashboard.dart
lib/screens/Profile/profile.dart
lib/screens/landing_page.dart
lib/services/profile_service.dart
lib/services/service_locator.dart
lib/services/storage_service.dart
pubspec.yaml

Added Service Locator and Fixed Side Drawer Error

---

lib/main.dart
lib/models/academic.dart
lib/screens/Academic/Check_Attendance/attendance.dart
lib/screens/Academic/Check_Dues/dues.dart
lib/screens/Academic/Current_Semester/current_semester_home_page.dart
lib/screens/Academic/Current_Semester/semester.dart
lib/screens/Academic/Registration/final_registration.dart
lib/screens/Academic/Registration/registration_home_page.dart
lib/screens/Academic/academic_home_page.dart
lib/services/academic_service.dart
lib/services/storage_service.dart

Adding Courses file not finished yet, will be added later.

Integrated Academic Module Information for Students

---

lib/screens/Establishment/establishment_home_page.dart
lib/screens/Gymkhana/GymkhanaHomepage.dart
lib/screens/Library/lib_home_screen.dart

Name and Student Type for all modules added. No UI changes.

Added profile data to modules

---

lib/models/academic_faculty.dart

Added Academic Faculty Model.
Waiting for the server to be reactivated for further work.

added academic-faculty model

---

lib/screens/Complaint/ComplaintHistory/complain_history.dart
lib/screens/Complaint/ComplaintHistory/complaints_card.dart
lib/screens/Complaint/ComplaintHistory/update_complaint.dart
lib/screens/Complaint/Constants/constants.dart
lib/screens/Complaint/LodgeComplaint/lodge_complaint.dart
lib/screens/Complaint/complaint.dart

<table>
<tr>
<td valign="top"><img src="https://user-images.githubusercontent.com/77340249/118838946-ba713380-b8e3-11eb-8688-a3fac8261a1b.jpeg"  width="200" height="400"></td>
<td valign="top"><img src="https://user-images.githubusercontent.com/77340249/118838956-bcd38d80-b8e3-11eb-8af5-96b90a258bd1.jpeg"  width="200" height="400"></td>
</tr>
</table>

Modified Update Complaint and Lodge Complaint Functionalities

---

lib/Components/pdf_view.dart
lib/screens/Academic/Current_Semester/academic_calendar.dart
lib/screens/Academic/Current_Semester/exam_time_table.dart
lib/screens/Academic/Current_Semester/list_of_holidays.dart
lib/screens/Academic/Current_Semester/time_table.dart
lib/screens/Academic/Registration/courses.dart
pubspec.yaml

Files added for Time Table, Academic Calendar, List of holidays and End Sem Time Table.
**Current Semester in sync with the web application as of 30-01-2022**

Academic: current semester

---

lib/screens/Academic/Current_Semester/academic_calendar.dart
lib/screens/Academic/Current_Semester/exam_time_table.dart
lib/screens/Academic/Current_Semester/list_of_holidays.dart

Removed duplicate tabs under calendar, time-table and list of holidays.

Academic current semester

---

lib/Components/tabBar_text_button.dart
lib/screens/Academic/Current_Semester/academic_calendar.dart
lib/screens/Academic/Current_Semester/exam_time_table.dart
lib/screens/Academic/Current_Semester/list_of_holidays.dart
lib/screens/Academic/Current_Semester/time_table.dart
lib/screens/Gymkhana/Club.dart
lib/screens/Gymkhana/clubsession.dart

[FIX] : Merged PR's issues

---

lib/screens/Academic/Current_Semester/academic_calendar.dart
lib/screens/Academic/Current_Semester/exam_time_table.dart
lib/screens/Academic/Current_Semester/list_of_holidays.dart
lib/screens/Academic/Current_Semester/time_table.dart

--fix: pdf view for current semester

FIX: pdf view for current semester

---

lib/Components/appBar.dart
lib/Components/side_drawer.dart
lib/Components/tabBar_children_with_text_button.dart
lib/constants.dart
lib/screens/Academic/Apply_for_Bonafide/bonafide.dart
lib/screens/Academic/Apply_for_Bonafide/pdf_services.dart
lib/screens/Academic/Current_Semester/academic_calendar.dart
lib/screens/Academic/Current_Semester/current_semester_home_page.dart
lib/screens/Academic/Current_Semester/exam_time_table.dart
lib/screens/Academic/Current_Semester/list_of_holidays.dart
lib/screens/Academic/Current_Semester/time_table.dart
lib/screens/Academic/Thesis/thesis_home_page.dart
lib/screens/Academic/academic_home_page.dart
lib/screens/Complaint/ComplaintHistory/complaints_card.dart
lib/screens/Complaint/ComplaintHistory/update_complaint.dart
lib/screens/Gymkhana/GymkhanaHomepage.dart
lib/screens/Gymkhana/clubsession.dart
lib/screens/Library/Book_Search.dart
lib/screens/Profile/profile.dart
lib/screens/landing_page.dart
lib/services/academic_service.dart
lib/services/complaint_service.dart
lib/services/dashboard_service.dart
lib/services/gymkhana_service.dart
lib/services/health_service.dart
lib/services/login_service.dart
lib/services/profile_service.dart

- refactored code with respect to guidelines shared

FIX: Code Refactor

---

lib/Components/side_drawer.dart

Dashboard taken out from modules in side drawer

---

android/app/build.gradle
lib/Components/side_drawer.dart
lib/api.dart
lib/screens/Academic/Apply_for_Bonafide/bonafide.dart
lib/screens/Academic/Current_Semester/semester.dart
lib/screens/Academic/academic_home_page.dart
lib/screens/Healthcenter/healthcentermodule.dart
lib/screens/LoginandDashboard/dashboard.dart
lib/services/complaint_service.dart
lib/services/storage_service.dart
pubspec.yaml

- api token auth issue fix
- academic procedures api null data fix
- bonafide hardcoded roll no fix

Merge dev with main

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
lib/api.dart

Server Url updated

---

android/build.gradle
android/gradle/wrapper/gradle-wrapper.properties
lib/Components/side_drawer.dart
lib/api.dart
lib/main.dart
lib/models/placement.dart
lib/screens/Placement_Cell/Add_Event.dart
lib/screens/Placement_Cell/Add_Placement_Record.dart
lib/screens/Placement_Cell/Batch_Statistics.dart
lib/screens/Placement_Cell/Past_Records.dart
lib/screens/Placement_Cell/Placement_Cell_Home.dart
lib/screens/Placement_Cell/Placement_Charts.dart
lib/screens/Placement_Cell/View_Placement_Records.dart
lib/services/placement_service.dart
pubspec.yaml

Added Screens for the Placement Cell and Integrated APIs.

SA-4 Implemented Placement Cell Module

---

android/build.gradle
lib/Components/appBar2.dart
lib/Components/bottom_navigation_bar.dart
lib/Components/side_drawer2.dart
lib/DesignationProvider.dart
lib/api.dart
lib/main.dart
lib/screens/LoginandDashboard/DashboardComponents/announcement.dart
lib/screens/LoginandDashboard/DashboardComponents/cardItems.dart
lib/screens/LoginandDashboard/DashboardComponents/news.dart
lib/screens/LoginandDashboard/DashboardComponents/notify.dart
lib/screens/LoginandDashboard/dashboard.dart
lib/screens/LoginandDashboard/login_page.dart
lib/services/appBar_services.dart
lib/services/dashboard_service.dart
lib/services/login_service.dart
lib/services/storage_service.dart

New feature implemented that involves the management of notifications, including the ability to delete, display, mark as read, and mark as unread.
PS: To test the feature, please use the changes from the latest dashboard and ensure that all files involved in the newly created feature are present.

Notification implemented
